export type Product = {
  slug: string
  name: string
  model: string
  brand: string
  category: string
  categorySlug: string
  image: string
  specs: { label: string; value: string }[]
  description: string
}

export const CATEGORIES = [
  { label: 'All Products', slug: 'all' },
  { label: 'Landline Phones', slug: 'landline-phones' },
  { label: 'Cordless Phones', slug: 'cordless-phones' },
  { label: 'CCTV Cameras', slug: 'cctv-cameras' },
  { label: 'EPABX Systems', slug: 'epabx-systems' },
  { label: 'Telephone Systems', slug: 'telephone-systems' },
]

export const PRODUCTS: Product[] = [
  // ─── LANDLINE PHONES ──────────────────────────────────────────────────────
  {
    slug: 'beetel-m56',
    name: 'Beetel M56 Caller ID Corded Landline Phone',
    model: 'M56',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365009914/OB/YA/FY/18199724/beetel-m56-caller-id-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M56' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Display', value: '16-Digit LCD' },
      { label: 'Speakerphone', value: 'Yes (2-way)' },
      { label: 'Caller ID', value: 'Yes' },
    ],
    description: 'The Beetel M56 features a 16-digit LCD display with caller ID and 2-way speakerphone. Ideal for home and office use with repeat incoming call display and durable ABS plastic build.',
  },
  {
    slug: 'beetel-b11',
    name: 'Beetel B11 Corded Landline Phone',
    model: 'B11',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/364999216/NX/EW/NG/18199724/beetel-b11-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'B11' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Functions', value: 'Mute, Pause, Flash, Redial' },
    ],
    description: 'Beetel B11 is a reliable corded landline phone with essential features including mute, pause, flash, and redial. Compact design suitable for home and small office use.',
  },
  {
    slug: 'beetel-b26',
    name: 'Beetel B26 Corded Slim Landline Phone',
    model: 'B26',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365009490/KJ/MG/CB/18199724/beetel-b26-corded-slim-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'B26' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Design', value: 'Slimline' },
      { label: 'Dialing', value: 'Tone / Pulse' },
    ],
    description: 'The Beetel B26 offers a slim, modern design with tone and pulse dialing capability. Its slimline form factor makes it perfect for desks with limited space.',
  },
  {
    slug: 'beetel-m59-black',
    name: 'Beetel M59 Caller ID Corded Landline Phone (Black)',
    model: 'M59',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365010375/BL/EX/FB/18199724/beetel-m59-caller-id-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M59' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Speakerphone', value: '2-Way' },
      { label: 'Caller ID', value: 'Yes' },
      { label: 'Do Not Disturb', value: 'Yes' },
    ],
    description: 'The Beetel M59 (Black) combines caller ID with a 2-way speakerphone and Do Not Disturb alarm. A reliable choice for offices needing clear communication and call management.',
  },
  {
    slug: 'beetel-b17',
    name: 'Beetel B17 Corded Landline Phone',
    model: 'B17',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365010889/FR/YJ/GJ/18199724/beetel-b17-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'B17' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Usage', value: 'Home' },
      { label: 'Wall Mountable', value: 'Yes' },
      { label: 'Dialing', value: 'Pulse-to-Tone Conversion' },
    ],
    description: 'Beetel B17 is a versatile home landline phone with wall mounting support and pulse-to-tone conversion, making it compatible with both older and modern telephone exchanges.',
  },
  {
    slug: 'beetel-m59-white',
    name: 'Beetel M59 Caller ID Corded Landline Phone (White)',
    model: 'M59',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365011330/EU/WG/EB/18199724/beetel-m59-caller-id-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M59' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Speakerphone', value: '2-Way' },
      { label: 'Caller ID', value: 'Yes' },
      { label: 'Security Lock', value: 'Yes' },
    ],
    description: 'The white variant of the Beetel M59 with caller ID, 2-way speakerphone, and a built-in security lock — great for reception desks and professional environments.',
  },
  {
    slug: 'beetel-m71',
    name: 'Beetel M71 Corded Landline Phone',
    model: 'M71',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365012012/XO/JC/ZT/18199724/beetel-m71-corded-landline-phone-white-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M71' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'The Beetel M71 is a clean, office-ready corded phone with a white finish. Reliable performance suitable for daily office communication needs.',
  },
  {
    slug: 'beetel-b15',
    name: 'Beetel B15 Landline Phone',
    model: 'B15',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/ANDROID/Default/2023/12/365687104/XP/UE/UV/18199724/product-jpeg-500x500.jpg',
    specs: [
      { label: 'Model', value: 'B15' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'Beetel B15 is a sturdy office landline phone with a classic black design. Built to last in demanding office environments with daily heavy use.',
  },
  {
    slug: 'beetel-m88',
    name: 'Beetel M88 Caller ID Corded Landline Phone',
    model: 'M88',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366436794/DO/BF/ES/18199724/beetel-m88-caller-id-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M88' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Caller ID', value: 'Yes' },
      { label: 'Usage', value: 'Office' },
      { label: 'Packaging', value: 'Box' },
    ],
    description: 'Beetel M88 with caller ID is a well-built office phone that comes securely packaged in a box. Suitable for multi-line office environments requiring call identification.',
  },
  {
    slug: 'beetel-m90',
    name: 'Beetel M90 Corded Landline Phone',
    model: 'M90',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/ANDROID/Default/2023/12/365634016/PE/PX/RL/18199724/product-jpeg-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M90' },
      { label: 'Color', value: 'White / Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'The Beetel M90 is available in both white and black and is designed for professional office environments. Durable construction with clear audio performance.',
  },
  {
    slug: 'beetel-b25',
    name: 'Beetel B25 Corded Landline Phone',
    model: 'B25',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366438332/RU/JC/OB/18199724/beetel-b25-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'B25' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'Beetel B25 is a dependable corded office phone with a compact black design. Offers clear audio and basic calling functions for everyday office use.',
  },
  {
    slug: 'beetel-m73',
    name: 'Beetel M73 Caller ID Corded Landline Phone',
    model: 'M73',
    brand: 'Beetel',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365013388/AA/VM/SK/18199724/beetel-m73-caller-id-corded-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'M73' },
      { label: 'Color', value: 'Black' },
      { label: 'Display', value: '16-Digit LCD with Blue Backlight' },
      { label: 'Caller ID', value: 'Yes' },
      { label: 'Usage', value: 'Office' },
      { label: 'Display Adjust', value: 'Adjustable Contrast' },
    ],
    description: 'The Beetel M73 stands out with its 16-digit blue backlit LCD display showing call details with adjustable contrast. Caller ID and solid build make it a top office pick.',
  },
  {
    slug: 'panasonic-kxtsc60mx',
    name: 'Panasonic KXTSC60MX Landline Phone',
    model: 'KXTSC60MX',
    brand: 'Panasonic',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434439/ON/PH/BF/18199724/panasonic-kxtsc60mx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTSC60MX' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'Panasonic KXTSC60MX is a reliable wired office phone in white. Known for Panasonic\'s audio clarity and build quality, it\'s ideal for professional office settings.',
  },
  {
    slug: 'panasonic-kxts880mx',
    name: 'Panasonic KXTS880MX Landline Phone',
    model: 'KXTS880MX',
    brand: 'Panasonic',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434284/IS/SB/FJ/18199724/panasonic-kxts880mx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTS880MX' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'The Panasonic KXTS880MX is a wired office phone featuring Panasonic\'s signature audio performance. Sleek black design with reliable connectivity for busy offices.',
  },
  {
    slug: 'panasonic-kxts820mx',
    name: 'Panasonic KXTS820MX Landline Phone',
    model: 'KXTS820MX',
    brand: 'Panasonic',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434161/WF/OW/KQ/18199724/panasonic-kxts820mx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTS820MX' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'Panasonic KXTS820MX is a wired office landline in black, well-suited for corporate environments demanding reliable telephony and premium Panasonic audio quality.',
  },
  {
    slug: 'panasonic-kxt2378mx',
    name: 'Panasonic KXT2378MX Landline Phone',
    model: 'KXT2378MX',
    brand: 'Panasonic',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434014/XU/IM/UJ/18199724/panasonic-kxt2378mx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXT2378MX' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'The Panasonic KXT2378MX wired office phone in white offers Panasonic\'s trusted durability and crystal-clear call quality for everyday office communication.',
  },
  {
    slug: 'panasonic-kxtsc62sx',
    name: 'Panasonic KXTSC62SX Landline Phone',
    model: 'KXTSC62SX',
    brand: 'Panasonic',
    category: 'Landline Phones',
    categorySlug: 'landline-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366433866/VZ/DU/ZM/18199724/panasonic-kxtsc62sx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTSC62SX' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
      { label: 'Usage', value: 'Office' },
    ],
    description: 'Panasonic KXTSC62SX is a wired office landline in black with Panasonic\'s hallmark durability, designed for high-call-volume office environments.',
  },

  // ─── CORDLESS PHONES ──────────────────────────────────────────────────────
  {
    slug: 'beetel-x73',
    name: 'Beetel X73 Cordless Landline Phone',
    model: 'X73',
    brand: 'Beetel',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365012617/AI/NF/YV/18199724/beetel-x73-cordless-2-4ghz-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'X73' },
      { label: 'Frequency', value: '2.4 GHz' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'White' },
      { label: 'Keypad', value: 'Illuminated' },
      { label: 'Phonebook', value: '50 Numbers with Names' },
    ],
    description: 'The Beetel X73 cordless phone operates on the 2.4 GHz band delivering 7 hours of talktime. Illuminated keypad and 50-name phonebook make it perfect for home use.',
  },
  {
    slug: 'panasonic-kxtg3411sx',
    name: 'Panasonic KXTG3411SX Cordless Phone',
    model: 'KXTG3411SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366515833/BW/DZ/GE/18199724/panasonic-kxtg3411sx-cordless-phone-500x500.png',
    specs: [
      { label: 'Model', value: 'KXTG3411SX' },
      { label: 'Frequency', value: '2.4 GHz' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'Panasonic KXTG3411SX offers 2.4 GHz wireless clarity with 7 hours of talktime. A trusted Panasonic cordless phone for reliable home and small office connectivity.',
  },
  {
    slug: 'panasonic-kxtg3811sx',
    name: 'Panasonic KXTG3811SX Cordless Phone',
    model: 'KXTG3811SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434671/BP/ZV/NL/18199724/panasonic-kxtg3811sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3811SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'The Panasonic KXTG3811SX cordless phone delivers 7 hours of talktime with Panasonic\'s signature audio fidelity. A dependable choice for home and office environments.',
  },
  {
    slug: 'panasonic-kxtg3821sx',
    name: 'Panasonic KXTG3821SX Cordless Phone',
    model: 'KXTG3821SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366435555/BN/NO/KS/18199724/panasonic-kxtg3821sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3821SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'Panasonic KXTG3821SX is a cordless phone with 7 hours talktime. Known for its build quality and crisp audio, ideal for daily use at home or in the office.',
  },
  {
    slug: 'panasonic-kxtg3711sx',
    name: 'Panasonic KXTG3711SX Cordless Phone',
    model: 'KXTG3711SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366435735/OK/CD/EA/18199724/panasonic-kxtg3711sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3711SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'The Panasonic KXTG3711SX cordless phone provides 7 hours of talktime and is built for reliable daily communication at home or in small offices.',
  },
  {
    slug: 'panasonic-kxtg3712sx',
    name: 'Panasonic KXTG3712SX Cordless Phone',
    model: 'KXTG3712SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366435882/XT/QF/XU/18199724/panasonic-kxtg3712sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3712SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'Panasonic KXTG3712SX is a reliable 2-handset cordless phone system offering 7 hours talktime — great for households that need multiple handsets.',
  },
  {
    slug: 'panasonic-kxtg3722sx',
    name: 'Panasonic KXTG3722SX Cordless Phone',
    model: 'KXTG3722SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366516774/WA/MF/JU/18199724/panasonic-kxtg3722sx-cordless-phone-500x500.png',
    specs: [
      { label: 'Model', value: 'KXTG3722SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'The Panasonic KXTG3722SX delivers 7 hours of talktime with clear wireless audio. A multi-handset cordless solution for connected homes and offices.',
  },
  {
    slug: 'panasonic-kxtg3721sx',
    name: 'Panasonic KXTG3721SX Cordless Phone',
    model: 'KXTG3721SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366436070/OH/IN/JD/18199724/panasonic-kxtg3721sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3721SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'Panasonic KXTG3721SX cordless phone provides 7 hours of talktime in a sleek black design, delivering excellent Panasonic audio quality for home and office users.',
  },
  {
    slug: 'panasonic-kxtg3411',
    name: 'Panasonic KXTG3411 Cordless Phone',
    model: 'KXTG3411',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366436234/NW/PV/DS/18199724/panasonic-kxtg3411-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3411' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'The Panasonic KXTG3411 is a proven cordless phone with 7 hours talktime. A straightforward, reliable unit for homes and small businesses.',
  },
  {
    slug: 'panasonic-kxtg3612sx',
    name: 'Panasonic KXTG3612SX Cordless Phone',
    model: 'KXTG3612SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366436511/GL/MY/PW/18199724/panasonic-kxtg3612sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3612SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'White' },
    ],
    description: 'Panasonic KXTG3612SX in white offers 7 hours talktime with Panasonic\'s reliable wireless performance. Clean design, ideal for home or reception areas.',
  },
  {
    slug: 'panasonic-kxtg3615sx',
    name: 'Panasonic KXTG3615SX Cordless Phone',
    model: 'KXTG3615SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366436627/QQ/OH/GP/18199724/panasonic-kxtg3615sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3615SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'The Panasonic KXTG3615SX is a multi-handset cordless system with 7 hours talktime — perfect for offices that need cordless coverage across multiple rooms.',
  },
  {
    slug: 'panasonic-kxtg3611sx',
    name: 'Panasonic KX TG3611SX Cordless Phone',
    model: 'KXTG3611SX',
    brand: 'Panasonic',
    category: 'Cordless Phones',
    categorySlug: 'cordless-phones',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366437093/XE/GL/SI/18199724/panasonic-kx-tg3611sx-cordless-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTG3611SX' },
      { label: 'Talktime', value: '7 Hours' },
      { label: 'Color', value: 'Black' },
    ],
    description: 'Panasonic KXTG3611SX is a dependable cordless phone with 7 hours talktime. A trusted Panasonic model for everyday cordless communication at home or in the office.',
  },

  // ─── CCTV CAMERAS ──────────────────────────────────────────────────────────
  {
    slug: 'hikvision-5mp-outdoor-dual-light',
    name: 'Hikvision 5MP Outdoor Dual Light Audio MIC Motion Alert CCTV Camera',
    model: 'DS-2CE76H0T-ITPFS',
    brand: 'Hikvision',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365002513/RV/DT/HZ/18199724/hikvision-5mp-outdoor-dual-light-audio-mic-motion-alert-wired-cctv-camera-500x500.jpg',
    specs: [
      { label: 'Resolution', value: '5 MP' },
      { label: 'Max Resolution', value: '1920 × 1080 Pixels' },
      { label: 'IR Range', value: '30 m' },
      { label: 'IP Rating', value: 'IP67' },
      { label: 'Audio', value: 'Built-in MIC' },
      { label: 'WDR', value: 'Digital WDR (3K)' },
      { label: 'Motion Alert', value: 'Yes' },
      { label: 'Installation', value: 'Outdoor' },
    ],
    description: 'The Hikvision 5MP Dual Light camera delivers outstanding outdoor surveillance with built-in audio MIC, motion alerts, IP67 weatherproofing, and 30m night vision range. Ideal for housing society gates, parking areas, and office exteriors.',
  },
  {
    slug: 'cp-plus-weatherproof-bullet',
    name: 'CP Plus Weatherproof Outdoor Wired Bullet Security Camera',
    model: 'CP-PLUS Bullet',
    brand: 'CP Plus',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365003344/JJ/GC/WI/18199724/cp-plus-weatherproof-outdoor-wired-bullet-security-camera-500x500.jpg',
    specs: [
      { label: 'Resolution', value: '2.4 MP' },
      { label: 'Video Quality', value: '1080p Full HD' },
      { label: 'IR Range', value: '20 m' },
      { label: 'WDR', value: 'D-WDR' },
      { label: 'Menu', value: 'OSD Menu' },
      { label: 'Installation', value: 'Outdoor' },
      { label: 'Type', value: 'Bullet' },
    ],
    description: 'CP Plus weatherproof bullet camera with 1080p Full HD resolution, 20m IR range, D-WDR, and OSD menu. A robust outdoor security solution for shops, society entrances, and commercial premises.',
  },
  {
    slug: 'cp-plus-infrared-5mp-dome',
    name: 'CP Plus Infrared HD 5MP Security Camera',
    model: 'CP-PLUS Dome',
    brand: 'CP Plus',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365003810/QM/GB/QL/18199724/cp-plus-infrared-hd-2-4mp-security-camera-500x500.jpg',
    specs: [
      { label: 'Resolution', value: '5 MP' },
      { label: 'Max Resolution', value: '1920 × 1080 Pixels' },
      { label: 'IR Range', value: '20 m' },
      { label: 'Type', value: 'Dome (Indoor)' },
      { label: 'Night Vision', value: 'Infrared' },
    ],
    description: 'CP Plus 5MP indoor dome camera with infrared night vision up to 20m. Perfect for offices, halls, corridors, and indoor spaces in housing societies requiring discreet surveillance.',
  },
  {
    slug: 'hikvision-2mp-dome',
    name: 'Hikvision 2MP Dome Camera',
    model: 'Hikvision Dome 2MP',
    brand: 'Hikvision',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/ANDROID/Default/2023/12/365695768/WW/TJ/YL/18199724/product-jpeg-500x500.jpg',
    specs: [
      { label: 'Resolution', value: '2 MP' },
      { label: 'Max Resolution', value: '1280 × 720' },
      { label: 'IR Range', value: '20 m' },
      { label: 'Technology', value: 'HDTVI / Turbo HD' },
      { label: 'Adjustment', value: '3-Axis' },
      { label: 'Type', value: 'Dome' },
    ],
    description: 'Hikvision 2MP Turbo HD dome camera with 3-axis adjustment for flexible installation. Ideal for indoor and semi-outdoor monitoring with reliable HDTVI technology and 20m IR night vision.',
  },
  {
    slug: 'hikvision-ds2ce76h0-5mp-dome',
    name: 'Hikvision DS2CE76H0TITPFS Ultra HD IR Wired CCTV Dome Camera 5MP',
    model: 'DS2CE76H0TITPFS',
    brand: 'Hikvision',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/365004368/JA/DH/WR/18199724/hikvision-ds-2ce76h0t-itpfs-ultra-hd-ir-wired-cctv-dome-camera-5mp-500x500.jpg',
    specs: [
      { label: 'Model', value: 'DS2CE76H0TITPFS' },
      { label: 'Resolution', value: '5 MP Ultra HD' },
      { label: 'Max Resolution', value: '1920 × 1080' },
      { label: 'IR Range', value: '20 m' },
      { label: 'Type', value: 'Dome' },
      { label: 'Connection', value: 'Wired' },
    ],
    description: 'The Hikvision DS2CE76H0TITPFS is a 5MP Ultra HD wired dome camera providing crisp surveillance footage indoors and outdoors. High-resolution imaging ensures clear identification of faces and number plates.',
  },
  {
    slug: 'hikvision-2mp-outdoor-mic',
    name: 'Hikvision 2MP Outdoor Wired HD Inbuilt Mic Camera',
    model: 'Hikvision 2MP Mic',
    brand: 'Hikvision',
    category: 'CCTV Cameras',
    categorySlug: 'cctv-cameras',
    image: 'https://5.imimg.com/data5/ANDROID/Default/2023/12/365695664/AM/XW/PZ/18199724/product-jpeg-500x500.jpg',
    specs: [
      { label: 'Resolution', value: '2 MP' },
      { label: 'Max Resolution', value: '1920 × 1080 Pixels' },
      { label: 'IR Range', value: '30 m' },
      { label: 'IP Rating', value: 'IP65' },
      { label: 'Sensor', value: 'CMOS' },
      { label: 'Audio', value: 'Built-in MIC' },
      { label: 'Installation', value: 'Outdoor' },
    ],
    description: 'Hikvision 2MP outdoor camera with built-in microphone, IP65 weatherproofing, and 30m IR range. CMOS sensor ensures reliable video capture for outdoor perimeter security.',
  },

  // ─── EPABX SYSTEMS ────────────────────────────────────────────────────────
  {
    slug: 'nec-sl2100-epabx',
    name: 'NEC SL2100 EPABX System',
    model: 'SL2100',
    brand: 'NEC',
    category: 'EPABX Systems',
    categorySlug: 'epabx-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/364995522/PL/JY/HL/18199724/nec-sl2100-epabx-system-500x500.jpg',
    specs: [
      { label: 'Model', value: 'SL2100' },
      { label: 'Brand', value: 'NEC' },
      { label: 'Usage', value: 'Small to Mid-Size Office' },
      { label: 'Display', value: 'LCD' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
    ],
    description: 'The NEC SL2100 EPABX is a feature-rich communication system designed for small to mid-size offices. It supports digital, IP, and analogue handsets on a single platform, with LCD display and expandable capacity for growing businesses.',
  },
  {
    slug: 'syntel-neos-epabx',
    name: 'Syntel Neos EPABX System',
    model: 'Neos',
    brand: 'Syntel',
    category: 'EPABX Systems',
    categorySlug: 'epabx-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366439601/EV/BW/XZ/18199724/syntel-neos-epabx-system-500x500.jpg',
    specs: [
      { label: 'Model', value: 'Neos' },
      { label: 'Brand', value: 'Syntel' },
      { label: 'Usage', value: 'Apartment / Office' },
      { label: 'Warranty', value: '1 Year' },
      { label: 'Color', value: 'Black' },
      { label: 'Expandable', value: 'Yes' },
    ],
    description: 'The Syntel Neos EPABX is a scalable system well-suited for apartments and offices. Its modular design allows line expansion at any point, making it a future-proof investment. Backed by a 1-year warranty.',
  },
  {
    slug: 'crystal-epabx',
    name: 'Crystal EPABX System',
    model: 'Crystal EPABX',
    brand: 'Crystal',
    category: 'EPABX Systems',
    categorySlug: 'epabx-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/364997826/BM/QO/MR/18199724/crystal-epabx-system-500x500.jpg',
    specs: [
      { label: 'Brand', value: 'Crystal' },
      { label: 'Lines Supported', value: '4' },
      { label: 'Usage', value: 'Small Office' },
      { label: 'Warranty', value: '1 Year' },
      { label: 'Color', value: 'Multicolor' },
      { label: 'Material', value: 'ABS Plastic' },
    ],
    description: 'The Crystal EPABX System supports 4 lines and is built for small office environments. Compact, affordable, and reliable with a 1-year warranty — a great entry-level EPABX solution.',
  },

  // ─── TELEPHONE SYSTEMS ────────────────────────────────────────────────────
  {
    slug: 'nec-sl2100-kts',
    name: 'NEC SL2100 KTS System',
    model: 'SL2100 KTS',
    brand: 'NEC',
    category: 'Telephone Systems',
    categorySlug: 'telephone-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366439247/KZ/CF/BA/18199724/nec-sl-2100-kts-system-500x500.jpg',
    specs: [
      { label: 'Model', value: 'SL2100 KTS' },
      { label: 'Brand', value: 'NEC' },
      { label: 'Weight', value: '0.4 kg' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
    ],
    description: 'The NEC SL2100 KTS (Key Telephone System) is a compact and powerful business communication system. Lightweight at 0.4 kg, it integrates seamlessly with the NEC SL2100 ecosystem for multi-line office telephony.',
  },
  {
    slug: 'panasonic-kxts500mx',
    name: 'Panasonic KXTS500MX Landline Phone',
    model: 'KXTS500MX',
    brand: 'Panasonic',
    category: 'Telephone Systems',
    categorySlug: 'telephone-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366519223/FH/LW/MU/18199724/panasonic-kxts500mx-landline-phone-500x500.png',
    specs: [
      { label: 'Model', value: 'KXTS500MX' },
      { label: 'Brand', value: 'Panasonic' },
      { label: 'Color', value: 'Black' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
    ],
    description: 'The Panasonic KXTS500MX is a wired telephone designed for office telephone systems. Reliable, clear audio and Panasonic\'s durability make it a popular choice for multi-line office setups.',
  },
  {
    slug: 'panasonic-kxts520mx',
    name: 'Panasonic KXTS520MX Landline Phone',
    model: 'KXTS520MX',
    brand: 'Panasonic',
    category: 'Telephone Systems',
    categorySlug: 'telephone-systems',
    image: 'https://5.imimg.com/data5/SELLER/Default/2023/12/366434572/WP/ZF/TT/18199724/panasonic-kxts520mx-landline-phone-500x500.jpg',
    specs: [
      { label: 'Model', value: 'KXTS520MX' },
      { label: 'Brand', value: 'Panasonic' },
      { label: 'Color', value: 'White' },
      { label: 'Material', value: 'ABS Plastic' },
      { label: 'Connectivity', value: 'Wired' },
    ],
    description: 'Panasonic KXTS520MX is a wired office telephone in white. Part of Panasonic\'s trusted office telephony range, it delivers clear audio and long-term reliability for professional environments.',
  },
]
